set up linters file:first commit
Ali-0111/final_Hello_Microverse pull request #1
Opened 2023-01-11 16:47 UTC by Ali-0111

ok, this will be reviewed by linters

2023-01-11 17:52 UTC, Ali-0111 commented on style.css
> +h1 {
This is my favorite color, for headers

2023-01-11 17:53 UTC, christianbiring1 requested changes
Hi @Ali-0111 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/211880540-2f57d1fe-eb6c-4231-9ad6-7de663edcca8.gif)


## Highlights
- [x] All linters checks are green :heavy_check_mark: 

## Required Changes ♻️
- [ ] Kindly you may consider giving your PR a descriptive `title` telling what the project aims to do.
`Hint: Hello microverse would sound greater! can't you tell?` :smile: 
- [ ] Also you may consider adding a summary in this box telling what changes were introduced in this PR.
![image](https://user-images.githubusercontent.com/97100091/211881237-60ce4308-0395-4d0b-8c9b-54eb58f83d18.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 17:53 UTC, christianbiring1 commented on README.md
> +  <br/>
[OPTIONAL]
- [ ] As said in the instruction, you can replace this log with your own, otherwise remove it.

2023-01-11 17:53 UTC, christianbiring1 commented on README.md
> +
- [ ] Kindly make sure your README is documented professionally. YOu may consider following the steps as shown in the template link:
```sh
- The project description: what the project aims to do
- Get Started: how to clone down and run the project on a local environment
- Stacks ...
```
- [ ] Kindly make sure you use the provided template and personalize it by applying what is relevant to your project.
You can find the template [here](https://github.com/microverseinc/readme-template)

2023-01-11 17:53 UTC, christianbiring1 commented on style.css
> +}
- [ ] As said in the project requirement, you may consider styling your header through a class. because that is the best practice to uniquely identify elements in your markup since it may happen you have more identic elements that you would like to have different styles
```html
<h1 class="text-header">Hello Microverse</h1>
```
```css
.text-header {
color: ...
}
```

2023-01-12 04:52 UTC, emmiiorji approved these changes
Hi @Ali-0111, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Congrats](https://user-images.githubusercontent.com/20554583/211860036-ec03abcf-8d2e-457c-948f-9afe812722fe.gif)

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Changes have been implemented


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-12 05:01 UTC, merged